2025-05-31 20:54:33,231 INFO    MainThread:20844 [wandb_setup.py:_flush():70] Current SDK version is 0.19.11
2025-05-31 20:54:33,231 INFO    MainThread:20844 [wandb_setup.py:_flush():70] Configure stats pid to 20844
2025-05-31 20:54:33,231 INFO    MainThread:20844 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Usuario\.config\wandb\settings
2025-05-31 20:54:33,231 INFO    MainThread:20844 [wandb_setup.py:_flush():70] Loading settings from C:\Users\Usuario\Trabajo Discretas pt2\wandb\settings
2025-05-31 20:54:33,231 INFO    MainThread:20844 [wandb_setup.py:_flush():70] Loading settings from environment variables
2025-05-31 20:54:33,232 INFO    MainThread:20844 [wandb_init.py:setup_run_log_directory():724] Logging user logs to C:\Users\Usuario\Trabajo Discretas pt2\wandb\run-20250531_205433-d1sj9bza\logs\debug.log
2025-05-31 20:54:33,232 INFO    MainThread:20844 [wandb_init.py:setup_run_log_directory():725] Logging internal logs to C:\Users\Usuario\Trabajo Discretas pt2\wandb\run-20250531_205433-d1sj9bza\logs\debug-internal.log
2025-05-31 20:54:33,232 INFO    MainThread:20844 [wandb_init.py:monkeypatch_ipython():643] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001EDD374BE50>
2025-05-31 20:54:33,232 INFO    MainThread:20844 [wandb_init.py:init():852] calling init triggers
2025-05-31 20:54:33,232 INFO    MainThread:20844 [wandb_init.py:init():857] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-31 20:54:33,232 INFO    MainThread:20844 [wandb_init.py:init():893] starting backend
2025-05-31 20:54:33,233 INFO    MainThread:20844 [wandb_init.py:init():897] sending inform_init request
2025-05-31 20:54:33,268 INFO    MainThread:20844 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=spawn, using: spawn
2025-05-31 20:54:33,268 INFO    MainThread:20844 [wandb_init.py:init():907] backend started and connected
2025-05-31 20:54:33,269 INFO    MainThread:20844 [wandb_run.py:_label_probe_notebook():1376] probe notebook
2025-05-31 20:54:33,270 INFO    MainThread:20844 [wandb_run.py:_label_probe_notebook():1386] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2025-05-31 20:54:33,270 INFO    MainThread:20844 [wandb_init.py:init():1005] updated telemetry
2025-05-31 20:54:33,272 INFO    MainThread:20844 [wandb_init.py:init():1029] communicating run to backend with 90.0 second timeout
2025-05-31 20:54:33,816 INFO    MainThread:20844 [wandb_init.py:init():1104] starting run threads in backend
2025-05-31 20:54:33,988 INFO    MainThread:20844 [wandb_run.py:_console_start():2573] atexit reg
2025-05-31 20:54:33,989 INFO    MainThread:20844 [wandb_run.py:_redirect():2421] redirect: wrap_raw
2025-05-31 20:54:33,989 INFO    MainThread:20844 [wandb_run.py:_redirect():2490] Wrapping output streams.
2025-05-31 20:54:33,989 INFO    MainThread:20844 [wandb_run.py:_redirect():2513] Redirects installed.
2025-05-31 20:54:33,993 INFO    MainThread:20844 [wandb_init.py:init():1150] run started, returning control to user process
2025-05-31 20:54:33,993 INFO    MainThread:20844 [wandb_run.py:_config_callback():1436] config_cb None None {'batch_size': 64, 'epochs': 100, 'device': 'cpu', 'hidden_dim': 152, 'lr': 0.001}
2025-06-01 11:54:01,820 INFO    MainThread:20844 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-01 11:54:01,998 INFO    MainThread:20844 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-01 11:54:01,999 INFO    MainThread:20844 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-01 11:54:02,014 INFO    MainThread:20844 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-01 11:54:02,024 INFO    MainThread:20844 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-01 11:54:02,025 INFO    MainThread:20844 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-01 11:54:02,042 INFO    MainThread:20844 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-01 11:54:02,057 INFO    MainThread:20844 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-01 11:54:02,057 INFO    MainThread:20844 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-01 11:54:02,071 INFO    MainThread:20844 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-01 11:54:02,089 INFO    MainThread:20844 [jupyter.py:save_ipynb():401] [no run ID] not saving jupyter notebook
2025-06-01 11:54:02,089 INFO    MainThread:20844 [wandb_init.py:_pre_run_cell_hook():602] [no run ID] pausing backend
2025-06-01 11:54:02,104 INFO    MainThread:20844 [wandb_init.py:_post_run_cell_hook():613] [no run ID] resuming backend
2025-06-01 11:54:03,215 WARNING MsgRouterThr:20844 [router.py:message_loop():63] [no run ID] message_loop has been closed
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 208, in _read_packet_bytes
    data = self._sock.recv(self._bufsize)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\router_sock.py", line 27, in _read_message
    return self._sock_client.read_server_response(timeout=1)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 235, in read_server_response
    data = self._read_packet_bytes(timeout=timeout)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 212, in _read_packet_bytes
    raise SockClientClosedError from e
wandb.sdk.lib.sock_client.SockClientClosedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\router.py", line 56, in message_loop
    msg = self._read_message()
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\router_sock.py", line 29, in _read_message
    raise MessageRouterClosedError from e
wandb.sdk.interface.router.MessageRouterClosedError
2025-06-01 11:54:03,253 INFO    MsgRouterThr:20844 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-06-01 11:54:03,269 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,354 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,355 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,356 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,356 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,357 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,369 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,370 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,371 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,371 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,372 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,372 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,373 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,373 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,374 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,375 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,375 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,376 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,376 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,377 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,378 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,378 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,379 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,380 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,380 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,381 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,381 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,382 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2025-06-01 11:54:03,383 ERROR   MainThread:20844 [redirect.py:_on_write():664] [no run ID] error in stderr callback
Traceback (most recent call last):
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\redirect.py", line 662, in _on_write
    cb(written_data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 2500, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 406, in wrapper
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 464, in wrapper_fn
    return func(self, *args, **kwargs)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\wandb_run.py", line 1639, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface.py", line 762, in publish_output_raw
    self._publish_output_raw(o)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\interface\interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 174, in send_record_publish
    self.send_server_request(server_req)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 154, in send_server_request
    self._send_message(msg)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 151, in _send_message
    self._sendall_with_error_handle(header + data)
  File "C:\Anaconda3\envs\AntorchaPy\lib\site-packages\wandb\sdk\lib\sock_client.py", line 130, in _sendall_with_error_handle
    sent = self._sock.send(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
